/* eslint-disable import/named */
import React from "react";
import "./globals.css";
import type { Metadata } from "next";
import { Font } from "next/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const GoogleFont = {
  subsets: ["latin"],
  variable: "--font-Rufina",
  weight: "700",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Font {...GoogleFont}>{children}</Font>
      </body>
    </html>
  );
}
