/* eslint-disable import/named */
import React from "react";
import "./globals.css";
import type { Metadata } from "next";
import ContextProvider from "@/context/global/GlobalContextProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ContextProvider>
        <body className="bg-[#081420]">{children}</body>
      </ContextProvider>
    </html>
  );
}
