const APIREFRESH: string = "APIREFRESH";
const SEARCHDATA: string = "SEARCHDATA";
const LOG_IN = "LOG_IN";
const AUTHENTICATION = "AUTHENTICATION";
const LOG_OUT = "LOG_OUT";

export { APIREFRESH, SEARCHDATA, LOG_IN, AUTHENTICATION, LOG_OUT };
